### ISSUE TITLE
支持dll调用,很多时候要想绕过cgo,dll调用似乎是最快捷的

### ISSUE THREAD

**Issue by aadog** [goplus/c2go#144]
支持dll调用,很多时候要想绕过cgo,dll调用似乎是最快捷的

**Comment by aadog** [comment]
希望支持 提供一个h头文件和dll调用

**Comment by xushiwei** [comment]
这个未来会考虑，短期不是重点

**Comment by aadog** [comment]
这是我手动包装的例子，提供参考
https://github.com/aadog/py3-go
